routes:
  -
    name: General auth route
    uris:
      - /iam*
    upstream_id: 2
    plugins:
      proxy-rewrite:
        regex_uri:
          - ^/iam(.*)
          - $1
  -
    uri: /iam/realms/web/protocol/openid-connect/certs
    upstream_id: 2
    plugins:
      proxy-cache:
        cache_http_status:
          - 200
        cache_key:
          - $request_uri
          - -cache-id
        cache_strategy: memory
        cache_ttl: 300
        cache_zone: memory_cache
        hide_cache_headers: false
  -
    uri: /http-bin/openid-connect/use-jwks/*
    upstream_id: 1
    plugins:
      proxy-rewrite:
        regex_uri:
          - ^/http-bin/openid-connect/use-jwks/(.*)
          - /$1
      openid-connect:
        client_id: apisix
        client_secret: gCUL3VS7N2weXuBPLT13HHQYeSUI163t
        discovery: http://keycloak:8080/auth/realms/web/.well-known/openid-configuration
        use_jwks: true
        bearer_only: true
        realm: web
  -
    uri: /http-bin/openid-connect/introspect/*
    upstream_id: 1
    plugins:
      proxy-rewrite:
        regex_uri:
          - ^/http-bin/openid-connect/introspect/(.*)
          - /$1
      openid-connect:
        client_id: apisix
        client_secret: gCUL3VS7N2weXuBPLT13HHQYeSUI163t
        discovery: http://keycloak:8080/auth/realms/web/.well-known/openid-configuration
        introspection_endpoint: http://keycloak:8080/auth/realms/web/protocol/openid-connect/token/introspect
        use_jwks: false
        introspection_endpoint_auth_method: client_secret_basic
        bearer_only: true
        realm: web
upstreams:
  - nodes:
      - weight: 1
        port: 80
        host: httpbin.org
    type: roundrobin
    name: HttpBin Upstream
    scheme: http
    id: 1
    keepalive_pool:
      requests: 1000
      size: 320
      idle_timeout: 60
    timeout:
      connect: 2
      send: 4
      read: 6
    pass_host: node
  - nodes:
      - weight: 1
        port: 8080
        host: keycloak
    type: roundrobin
    name: Keycloak Upstream
    scheme: http
    id: 2
    keepalive_pool:
      requests: 1000
      size: 320
      idle_timeout: 60
    timeout:
      connect: 2
      send: 4
      read: 6
    pass_host: node
#END