routes:
  -
    uris:
      - /auth/*
    upstream_id: 2
  -
    uri: /auth/realms/csr/protocol/openid-connect/certs
    upstream_id: 2
    plugins:
      proxy-cache:
        cache_http_status:
          - 200
        cache_key:
          - $request_uri
          - -cache-id
        cache_strategy: memory
        cache_ttl: 300
        cache_zone: memory_cache
        hide_cache_headers: false
  -
    uri: /auth/realms/csr/protocol/openid-connect/auth
    upstream_id: 2
    plugins:
      openid-connect:
        client_id: apisix
        client_secret: gCUL3VS7N2weXuBPLT13HHQYeSUI163t
        discovery: http://keycloak:8080/auth/realms/csr/.well-known/openid-configuration
        bearer_only: false
        realm: csr
        redirect_uri: http://localhost:3000
        introspection_endpoint_auth_method: client_secret_post
        session:
          secret: ZjNlNWEwZmItYjdjYy00MmE3LTg4YTEtZWZhMjMzYWRhMGE5
  -
    uri: /http-bin/openid-connect/use-jwks/*
    upstream_id: 1
    plugins:
      proxy-rewrite:
        regex_uri:
          - ^/http-bin/openid-connect/use-jwks/(.*)
          - /$1
      openid-connect:
        client_id: apisix
        client_secret: gCUL3VS7N2weXuBPLT13HHQYeSUI163t
        discovery: http://keycloak:8080/auth/realms/csr/.well-known/openid-configuration
        use_jwks: true
        bearer_only: true
        realm: csr
  -
    uri: /http-bin/openid-connect/introspect/*
    upstream_id: 1
    plugins:
      proxy-rewrite:
        regex_uri:
          - ^/http-bin/openid-connect/introspect/(.*)
          - /$1
      openid-connect:
        client_id: apisix
        client_secret: gCUL3VS7N2weXuBPLT13HHQYeSUI163t
        discovery: http://keycloak:8080/auth/realms/csr/.well-known/openid-configuration
        introspection_endpoint: http://keycloak:8080/auth/realms/csr/protocol/openid-connect/token/introspect
        use_jwks: false
        introspection_endpoint_auth_method: client_secret_basic
        bearer_only: true
        realm: csr
upstreams:
  - nodes:
      - weight: 1
        port: 80
        host: httpbin.org
    type: roundrobin
    name: HttpBin Upstream
    scheme: http
    id: 1
    keepalive_pool:
      requests: 1000
      size: 320
      idle_timeout: 60
    timeout:
      connect: 2
      send: 4
      read: 6
    pass_host: node
  - nodes:
      - weight: 1
        port: 8080
        host: keycloak
    type: roundrobin
    name: Keycloak Upstream
    scheme: http
    id: 2
    keepalive_pool:
      requests: 1000
      size: 320
      idle_timeout: 60
    timeout:
      connect: 2
      send: 4
      read: 6
    pass_host: node
#END